### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by prashantmital**

### CODE REVIEW

**Comment by noraderam** [comment]
What was the merge conflict? Would the release commit be missing anything because the merge happened afterwards?

**Comment by noraderam** [comment]
Content-wise this looks good

**Comment by prashantmital** [comment]
@noraderam no there wouldn't be anything missing. I just corrected the `MAJOR`, `MINOR` values in the base maintenance branch (which are also changed by the release itself) which caused a conflict. The commit to be tagged is clean and will work.

**Comment by prashantmital** [comment]
Merging.

**Pull request merged**
